apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer

metadata:
  name: letsencrypt-issuer

spec:
  acme:
    server: {{ .Values.acmeServer }}
    email: julio@blackdevs.com.br

    privateKeySecretRef:
      name: letsencrypt-issuer

    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
