sudo: false

os:
- linux

dist: bionic

branches:
  only:
  - master

services:
  - docker

env:
  # set environment
  - SHA=$(git rev-parse --short=7 HEAD)

# before_install:
#   # terraform lintet
#   - docker image pull wata727/tflint:0.14.0
#   - docker run --name tflint --rm -v $PWD:/data --entrypoint "" -it wata727/tflint:0.14.0 tflint ./

#   # terraform security
#   - docker image pull wesleydeanflexion/tfsec:latest
#   - docker run --name tfsec --rm -v "$PWD:/workdir" -it wesleydeanflexion/tfsec:latest .

#   # shell linter
#   - docker pull koalaman/shellcheck-alpine:stable
#   - docker run --name shellcheck --rm -v $PWD:/mnt -it koalaman/shellcheck:stable ./*.sh

script:
  # terraform validate and init
  - docker run --name terraform --rm -v $PWD:/data -it
      --entrypoint "" hashicorp/terraform:0.12.24
      sh -c "cd /data && terraform init && terraform validate"

# deploy:
#   provider: script
#   script: deploy.sh
#   on:
#     branch: master

after_success:
  # TODO: add plan output in comment with tfmask
  - if [ $TRAVIS_BRANCH == "master" ]; then echo "MASTER"; fi
  - if [ $TRAVIS_PULL_REQUEST != "false" ]; then
      docker run -i --rm
        -e GITHUB_TOKEN=$GITHUB_TOKEN
        -e GITHUB_OWNER=julio-cesar-development
        -e GITHUB_REPO=terraform-k8s-do
        -e GITHUB_COMMENT_TYPE=pr
        -e GITHUB_PR_ISSUE_NUMBER=$TRAVIS_PULL_REQUEST
        -e GITHUB_COMMENT_FORMAT="Comment {{.}}"
        -e GITHUB_COMMENT="Build $SHA was successful"
        cloudposse/github-commenter:latest
      ;
    fi

after_failure:
  - if [ $TRAVIS_BRANCH == "master" ]; then echo "MASTER"; fi
  - if [ $TRAVIS_PULL_REQUEST != "false" ]; then
      docker run -i --rm
        -e GITHUB_TOKEN=$GITHUB_TOKEN
        -e GITHUB_OWNER=julio-cesar-development
        -e GITHUB_REPO=terraform-k8s-do
        -e GITHUB_COMMENT_TYPE=pr
        -e GITHUB_PR_ISSUE_NUMBER=$TRAVIS_PULL_REQUEST
        -e GITHUB_COMMENT_FORMAT="Comment {{.}}"
        -e GITHUB_COMMENT="Build $SHA was not successful"
        cloudposse/github-commenter:latest
      ;
    fi
