language: shell # minimal

os:
  - linux

dist: bionic

branches:
  only:
    - master
    - development

services:
  - docker

env:
  # set environment
  - SHA=$(git rev-parse --short=7 HEAD) FULL_SHA=$(git rev-parse HEAD) REPO_NAME="terraform-k8s-do" CLUSTER_NAME="k8s-cluster" AWS_BUCKET_NAME="blackdevs-aws" AWS_DEFAULT_REGION="sa-east-1"

script:
  - |
    # terraform linter
    docker container run --name tflint --rm -v "$PWD/infrastructure:/data" -w /data --entrypoint "" -it wata727/tflint:0.14.0 tflint ./
    docker container run --name tflint --rm -v "$PWD/application:/data" -w /data --entrypoint "" -it wata727/tflint:0.14.0 tflint ./

    # terraform security
    docker container run --name tfsec --rm -v "$PWD/infrastructure:/data" -w /data --user 1000 -it wesleydeanflexion/tfsec:latest .
    docker container run --name tfsec --rm -v "$PWD/application:/data" -w /data --user 1000 -it wesleydeanflexion/tfsec:latest .

    # shell linter
    docker container run --name shellcheck \
      --rm -v "$PWD:/data" \
      -w /data -it koalaman/shellcheck-alpine:stable \
      sh -c "shellcheck deploy.sh && \
        shellcheck infrastructure/deploy.sh && \
        shellcheck application/deploy.sh"

after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST != "false" ]; then
      docker container run -i --rm \
        --env GITHUB_TOKEN=$GITHUB_TOKEN \
        --env GITHUB_OWNER=julio-cesar-development \
        --env GITHUB_REPO=$REPO_NAME \
        --env GITHUB_COMMENT_TYPE=pr \
        --env GITHUB_PR_ISSUE_NUMBER=$TRAVIS_PULL_REQUEST \
        --env GITHUB_COMMENT_FORMAT="<b>Comment</b><br/>{{.}}" \
        --env GITHUB_COMMENT="build of commit $SHA was successful, LGTM" \
        cloudposse/github-commenter:latest

        echo "{\"commit_id\": \"$FULL_SHA\", \"body\": \"Approved\", \"event\": \"APPROVE\"}" > payload.json

        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/julio-cesar-development/$REPO_NAME/pulls/$TRAVIS_PULL_REQUEST/reviews \
          -d "@payload.json"
    fi

after_failure:
  - |
    if [ $TRAVIS_PULL_REQUEST != "false" ]; then
      docker container run -i --rm \
        --env GITHUB_TOKEN=$GITHUB_TOKEN \
        --env GITHUB_OWNER=julio-cesar-development \
        --env GITHUB_REPO=$REPO_NAME \
        --env GITHUB_COMMENT_TYPE=pr \
        --env GITHUB_PR_ISSUE_NUMBER=$TRAVIS_PULL_REQUEST \
        --env GITHUB_COMMENT_FORMAT="<b>Comment</b><br/>{{.}}" \
        --env GITHUB_COMMENT="build of commit $SHA was not successful" \
        cloudposse/github-commenter:latest

      echo "{\"commit_id\": \"$FULL_SHA\", \"body\": \"Requested changes\", \"event\": \"REQUEST_CHANGES\"}" > payload.json

      curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $GITHUB_TOKEN" \
        https://api.github.com/repos/julio-cesar-development/$REPO_NAME/pulls/$TRAVIS_PULL_REQUEST/reviews \
        -d "@payload.json"
    fi

# deploy:
#   on:
#     branch: master
#   provider: script
#   script: bash ./deploy.sh
#   skip_cleanup: true

# after_deploy:
#   - |
#     docker container run \
#       --name awscli \
#       --rm -it \
#       -v "$PWD/infrastructure:/data" \
#       -w /data \
#       --env AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
#       --env AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
#       --env AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" \
#       --env CLUSTER_NAME="$CLUSTER_NAME" \
#       --entrypoint "" \
#       amazon/aws-cli:2.0.20 sh -c \
#       "aws s3 cp ./plan.tfplan s3://${AWS_BUCKET_NAME}/terraform/k8s-do/plan.tfplan && \
#       aws s3 cp ./plan.txt s3://${AWS_BUCKET_NAME}/terraform/k8s-do/plan.txt && \
#       aws s3 cp ./apply.txt s3://${AWS_BUCKET_NAME}/terraform/k8s-do/apply.txt && \
#       aws s3 cp ./${CLUSTER_NAME}-kubeconfig.yaml s3://${AWS_BUCKET_NAME}/terraform/k8s-do/${CLUSTER_NAME}-kubeconfig.yaml"
