todoapp:
    secrets:
        NODE_ENV: ENC[AES256_GCM,data:FhQV4qA=,iv:Hwx06mlp+WL3mPmVYLoJLMb7puOF+ITUOkdFyOx7AbM=,tag:6B5QHH1MRWVYr+JtjHFNiQ==,type:str]
digitalocean:
    secrets:
        apiToken: ENC[AES256_GCM,data:IILuogFuP+wvtAw0L7XEVxtht0O687Tjxkztr3yhNyeBy1mS9TdbZcic3oFxn8XHt/17JiyzAsqM11SU5Y2XCw==,iv:4aVHuVbaRDvBHVS7Rr2dq2/yrJ8igZImTBrYD3sAWFI=,tag:u0QPxvi/43/PbvCTfQ/qqA==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:sa-east-1:829560024531:key/8c7bb497-873b-438d-a825-0526713496b8
        created_at: '2020-11-28T03:56:25Z'
        enc: AQICAHhLagC2ioliXud9AogMJA/s1tkWk6BJnr1lnGuDz6q4zwHXKyhZqR/HjB6XGXRFvwsoAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+PUbYx9+Gb49cf/FAgEQgDvMIl0hWr7VMNs7w+Cx7WsRcARqbDw4EPoIMGJOsD15FYHEQxEYThMIZZ6BSgrnArA9cziMgnGeAOfihA==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-28T03:56:26Z'
    mac: ENC[AES256_GCM,data:S5c9CAStt3F8hcMl3AKmd0TU0fC6kwPF9KqMIJXh2/2vaJ5EAbtEIraOz7dVBWehWFYbKExcDqInHwskXjxufDd/c5qU70qcMzxU8Rm+sGAFeY6gJCe961anlk/Rx6W+s0RBjX3AkcZHZQ9GrPZ8PU6ygPmAemr1oOe8E1mFZdU=,iv:mDWKlOV+CUXtD+YtlA0kYg5XW1gmaMjp46GYdPJrhMI=,tag:MWIFzMuiC5Rsq+AuYXr+jA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
