version: v1.0.0

todoapp:
  replicaCount: 1
  namespace: todoapp
  containerPort: 80
  image:
    repository: juliocesarmidia/todo-vue
    tag: latest
    imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: todoapp-port
  resources:
    requests:
      memory: "128Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "300m"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    external-dns.alpha.kubernetes.io/ttl: "30"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: todoapp
  hosts:
    - invalid
  tls:
    - secretName: todoapp-tls
      hosts:
        - invalid

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

config: {}

secrets: {}

nodeSelector: {}

tolerations: []

affinity: {}